# -*- coding: utf-8 -*-
"""Data Pipelines with Python and PostgreSQ_Wk7_project_Nancy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCoBxvwg4ToXqbsXyBdJQ9i1vNsu0sSC
"""

import pandas as pd
import numpy as np
import psycopg2

# Data extraction
equipment_data = pd.read_csv('/content/equipment_sensor.csv')
maintenance_data = pd.read_csv('/content/maintenance_records.csv')
network_data = pd.read_csv('/content/network_sensor.csv')

# Transforming the data 

# Remove duplicates from equipment data
equipment_data.drop_duplicates(inplace=True)
maintenance_data.drop_duplicates(inplace=True)
network_data.drop_duplicates(inplace=True)

# Filling the missing values
equipment_data.fillna(method='ffill', inplace=True)
maintenance_data.fillna(method='ffill', inplace=True)
network_data.fillna(method='ffill', inplace=True)

# Normalizing sensor readings
equipment_data['sensor_reading'] = (equipment_data['sensor_reading'] - np.mean(equipment_data['sensor_reading'])) / np.std(equipment_data['sensor_reading'])
network_data['sensor_reading'] = (network_data['sensor_reading'] - np.mean(network_data['sensor_reading'])) / np.std(network_data['sensor_reading'])

# Aggregate the equipment data to get the total number of equipment failures
equipment_failures = equipment_data.groupby(['ID']).size().reset_index(name='total_failures')

# Aggregate the equipment data to get the average time between failures
equipment_data['datetime'] = pd.to_datetime(equipment_data['date'] + ' ' + equipment_data['time'])
equipment_data['time_between_failures'] = equipment_data.groupby(['ID'])['datetime'].diff()
equipment_data['time_between_failures'] = equipment_data['time_between_failures'].dt.total_seconds() / 3600
equipment_avg_time_between_failures = equipment_data.groupby(['ID'])['time_between_failures'].mean().reset_index(name='avg_time_between_failures')

# Join the datasets
df_joined = pd.concat([equipment_data, network_data, maintenance_data], axis=0)

#Data loading to postgreSQL database 
!curl ipecho.net/plain

pip install psycopg2

conn = psycopg2.connect(
    host="34.70.185.0",
    database="karimiproj1",
    user="nancy",
    password="nancy"
)

# Create a cursor object
cursor = conn.cursor()